### ISSUE TITLE
Allow sub-branches

### ISSUE THREAD

**Issue by thewoolleyman** [pivotaltracker/git-branches-resource#3]
Publish a new docker image containing https://github.com/pivotaltracker/git-branches-resource/pull/2

**Comment by thewoolleyman** [comment]
@louis-paul @dflor003 @johnrjj @trebolcinco @futureturnip - I just pushed a [new docker `latest` tag](https://hub.docker.com/r/tracker/git-branches-resource) that contains PR https://github.com/pivotaltracker/git-branches-resource/pull/2.

Please give it a try, and let me know if it works, or if I broke anything.  I also tried to make some tags of the prior versions (tagged in git at `0.N.0`), so hopefully older versions are still usable too.

FYI, I'm not running an installation of this anymore, and my Docker-fu is not great, so please let me know if I broke things.  But, I'm happy to continue accepting and releasing pull requests, with the caveat that I can't test them myself.

-- Chad

**Comment by louis-paul** [comment]
@thewoolleyman Works for us, our current CBM pipelines do as usual and now detect sub-branches properly. Thanks!
