### ISSUE TITLE
Check resource does not work

### ISSUE THREAD

**Issue by pk0024703** [pivotaltracker/git-branches-resource#4]
i Have configured this resource for my branch manager tool, everytime new branch is created, the branch manager does not auto run as the git-branches resource is not checking. 
 below is my yaml
-------------------------------
jobs:
- name: branch-manager
  serial: true
  plan:
  - get: concourse-branch-manager
    params: {depth: 20}
    trigger: true
  - get: git-branches
    resource: branch-manager-git-branches
    trigger: true
  - get: template-repo
    resource: branch-manager-ci-repo
    trigger: true
  - get: credentials-repo
    resource: branch-manager-credentials
    params: {depth: 20}
    trigger: true
  - get: config-repo
    resource: branch-manager-ci-repo
    params: {depth: 20, submodules: none}
    trigger: true
  - task: manage-branches
    file: concourse-branch-manager/tasks/manage-branches.yml

**Comment by thewoolleyman** [comment]
Per the README, this project is no longer maintained.  I recommend you look into the upcoming Spatial Resources feature of Concourse.  Good luck!
